/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 shoe.gltf --transform 
Files: shoe.gltf [3.4MB] > shoe-transformed.glb [2.09MB] (38%)
Author: Qlone (https://sketchfab.com/Qlone)
License: CC-BY-ND-4.0 (http://creativecommons.org/licenses/by-nd/4.0/)
Source: https://sketchfab.com/3d-models/nike-air-max-sequent-2fe05058b31e4856a241b1ca3008f7f4
Title: Nike Air Max Sequent
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/shoe-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.material0} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/shoe-transformed.glb')
